logs:
  level: debug
  encode: console #json or console
  initFields:
    package: hello_world.v1
    server: hello-world-server
    version: 0.1.0
  file:
    maxSize: 100
    maxBackups: 10
    maxAge: 28