version: "2"
services:
  question:
    build:
      context: ..
      dockerfile: question/Dockerfile
    container_name: question
    ports:
    - 8800:8082
    restart: always
    volumes:
    - .:/go/src/github.com/liankui/prenatal-server
