components:
  schemas:
    hello_world.v1.Echo:
      description: echo object
      properties:
        message:
          description: the completed echo message
          title: mojo.core.String
          type: string
        name:
          description: the echo name
          title: mojo.core.String
          type: string
      title: hello_world.v1.Echo
      type: object
info:
  description: will do a simple echo
  title: hello world service
  version: 0.1.0
openapi: 3.0.3
paths:
  /hello-world/v1/echos/{name}:
    get:
      description: ""
      operationId: get_echo
      parameters:
      - description: echo name
        in: path
        name: name
        schema:
          title: mojo.core.String
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hello_world.v1.Echo'
          description: OK
      summary: say hello to the name
