// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello-world/v1/echo.proto

package org.mojo-lang.hello_world.v1;

public final class EchoProto {
  private EchoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hello_world_v1_Echo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hello_world_v1_Echo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031hello-world/v1/echo.proto\022\016hello_world" +
      ".v1\"%\n\004Echo\022\014\n\004name\030\001 \001(\t\022\017\n\007message\030\002 \001" +
      "(\tBs\n\034org.mojo-lang.hello_world.v1B\tEcho" +
      "ProtoP\001ZFgit.company.com/examples/hello-" +
      "world/go/pkg/hello-world/v1;hello_worldb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_hello_world_v1_Echo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hello_world_v1_Echo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hello_world_v1_Echo_descriptor,
        new java.lang.String[] { "Name", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
