// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello-world/v1/hello_world.proto

package org.mojo-lang.hello_world.v1;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hello_world_v1_GetEchoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hello_world_v1_GetEchoRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n hello-world/v1/hello_world.proto\022\016hell" +
      "o_world.v1\032\031hello-world/v1/echo.proto\"\036\n" +
      "\016GetEchoRequest\022\014\n\004name\030\001 \001(\t2N\n\nHelloWo" +
      "rld\022@\n\010get_echo\022\036.hello_world.v1.GetEcho" +
      "Request\032\024.hello_world.v1.EchoBy\n\034org.moj" +
      "o-lang.hello_world.v1B\017HelloWorldProtoP\001" +
      "ZFgit.company.com/examples/hello-world/g" +
      "o/pkg/hello-world/v1;hello_worldb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojo-lang.hello_world.v1.EchoProto.getDescriptor(),
        });
    internal_static_hello_world_v1_GetEchoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hello_world_v1_GetEchoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hello_world_v1_GetEchoRequest_descriptor,
        new java.lang.String[] { "Name", });
    org.mojo-lang.hello_world.v1.EchoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
