components:
  schemas:
    mojo.core.Timestamp:
      description: ""
      format: Timestamp
      title: mojo.core.Timestamp
      type: string
    prenatal.Answer:
      description: ""
      properties:
        answer:
          title: mojo.core.String
          type: string
        correctAnswer:
          title: mojo.core.String
          type: string
        createTime:
          $ref: '#/components/schemas/mojo.core.Timestamp'
        id:
          title: mojo.core.String
          type: string
        questionCategory:
          title: mojo.core.String
          type: string
        questionId:
          title: mojo.core.String
          type: string
        updateTime:
          $ref: '#/components/schemas/mojo.core.Timestamp'
        userId:
          title: mojo.core.String
          type: string
        userName:
          title: mojo.core.String
          type: string
      title: prenatal.Answer
      type: object
    prenatal.Comment:
      description: ""
      properties:
        comment:
          title: mojo.core.String
          type: string
        createTime:
          $ref: '#/components/schemas/mojo.core.Timestamp'
        id:
          title: mojo.core.String
          type: string
        likes:
          format: Int64
          title: mojo.core.Int64
          type: integer
        parentCommentId:
          title: mojo.core.String
          type: string
        questionCategory:
          title: mojo.core.String
          type: string
        questionId:
          title: mojo.core.String
          type: string
        updateTime:
          $ref: '#/components/schemas/mojo.core.Timestamp'
        userId:
          title: mojo.core.String
          type: string
        userName:
          title: mojo.core.String
          type: string
      title: prenatal.Comment
      type: object
    prenatal.Question:
      description: ""
      properties:
        category:
          title: mojo.core.String
          type: string
        createTime:
          $ref: '#/components/schemas/mojo.core.Timestamp'
        explanation:
          title: mojo.core.String
          type: string
        id:
          title: mojo.core.String
          type: string
        options:
          items:
            $ref: '#/components/schemas/prenatal.QuestionOption'
          title: mojo.core.Array
          type: array
        question:
          title: mojo.core.String
          type: string
        updateTime:
          $ref: '#/components/schemas/mojo.core.Timestamp'
        userId:
          title: mojo.core.String
          type: string
        userName:
          title: mojo.core.String
          type: string
      title: prenatal.Question
      type: object
    prenatal.QuestionOption:
      description: ""
      properties:
        content:
          description: 选项的描述
          title: mojo.core.String
          type: string
        createTime:
          $ref: '#/components/schemas/mojo.core.Timestamp'
        explanation:
          title: mojo.core.String
          type: string
        id:
          title: mojo.core.String
          type: string
        isCorrect:
          title: mojo.core.Bool
          type: boolean
        option:
          description: 选项
          title: mojo.core.String
          type: string
        questionCategory:
          title: mojo.core.String
          type: string
        questionId:
          title: mojo.core.String
          type: string
        updateTime:
          $ref: '#/components/schemas/mojo.core.Timestamp'
      title: prenatal.QuestionOption
      type: object
info:
  description: quiz服务相关的接口
  title: quiz服务
  version: 0.1.0
openapi: 3.0.3
paths:
  /v1/Answers:
    post:
      description: ""
      operationId: create_answer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/prenatal.Answer'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/prenatal.Answer'
          description: OK
      summary: 新增answer
  /v1/questions:
    post:
      description: ""
      operationId: create_question
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/prenatal.Question'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/prenatal.Question'
          description: OK
      summary: 新增question信息
  /v1/questions/{id}:
    delete:
      description: ""
      operationId: delete_question
      parameters:
      - in: path
        name: id
        schema:
          title: mojo.core.String
          type: string
      responses:
        "200":
          description: OK
      summary: 删除question
    get:
      description: ""
      operationId: get_question
      parameters:
      - in: path
        name: id
        schema:
          title: mojo.core.String
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/prenatal.Question'
          description: OK
      summary: 获取question信息
    put:
      description: ""
      operationId: update_question
      parameters:
      - in: path
        name: id
        schema:
          title: mojo.core.String
          type: string
      - in: query
        name: question
        schema:
          $ref: '#/components/schemas/prenatal.Question'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/prenatal.Question'
          description: OK
      summary: 更新question信息
