// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello-world/v1/echo.proto

package org.mojo-lang.hello_world.v1;

public interface EchoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hello_world.v1.Echo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
