// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello-world/v1/hello_world.proto

package org.mojo-lang.hello_world.v1;

public interface GetEchoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hello_world.v1.GetEchoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
