// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/v1/user.proto

package user.v1;

public interface GetUserinfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.v1.GetUserinfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
