// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/v1/userinfo.proto

package user.v1;

public interface UserinfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.v1.Userinfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string password = 10;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 10;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string email = 11;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 11;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string phoneNumber = 12;</code>
   * @return The phoneNumber.
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>string phoneNumber = 12;</code>
   * @return The bytes for phoneNumber.
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();

  /**
   * <code>string industry = 13;</code>
   * @return The industry.
   */
  java.lang.String getIndustry();
  /**
   * <code>string industry = 13;</code>
   * @return The bytes for industry.
   */
  com.google.protobuf.ByteString
      getIndustryBytes();

  /**
   * <code>string company = 21;</code>
   * @return The company.
   */
  java.lang.String getCompany();
  /**
   * <code>string company = 21;</code>
   * @return The bytes for company.
   */
  com.google.protobuf.ByteString
      getCompanyBytes();

  /**
   * <code>string job = 22;</code>
   * @return The job.
   */
  java.lang.String getJob();
  /**
   * <code>string job = 22;</code>
   * @return The bytes for job.
   */
  com.google.protobuf.ByteString
      getJobBytes();

  /**
   * <code>string role = 23;</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <code>string role = 23;</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();

  /**
   * <code>string birthday = 24;</code>
   * @return The birthday.
   */
  java.lang.String getBirthday();
  /**
   * <code>string birthday = 24;</code>
   * @return The bytes for birthday.
   */
  com.google.protobuf.ByteString
      getBirthdayBytes();

  /**
   * <code>string education = 25;</code>
   * @return The education.
   */
  java.lang.String getEducation();
  /**
   * <code>string education = 25;</code>
   * @return The bytes for education.
   */
  com.google.protobuf.ByteString
      getEducationBytes();

  /**
   * <code>string major = 26;</code>
   * @return The major.
   */
  java.lang.String getMajor();
  /**
   * <code>string major = 26;</code>
   * @return The bytes for major.
   */
  com.google.protobuf.ByteString
      getMajorBytes();

  /**
   * <code>string openid = 51;</code>
   * @return The openid.
   */
  java.lang.String getOpenid();
  /**
   * <code>string openid = 51;</code>
   * @return The bytes for openid.
   */
  com.google.protobuf.ByteString
      getOpenidBytes();

  /**
   * <code>string unionid = 52;</code>
   * @return The unionid.
   */
  java.lang.String getUnionid();
  /**
   * <code>string unionid = 52;</code>
   * @return The bytes for unionid.
   */
  com.google.protobuf.ByteString
      getUnionidBytes();

  /**
   * <code>string nickname = 53;</code>
   * @return The nickname.
   */
  java.lang.String getNickname();
  /**
   * <code>string nickname = 53;</code>
   * @return The bytes for nickname.
   */
  com.google.protobuf.ByteString
      getNicknameBytes();

  /**
   * <code>string avatarUrl = 54;</code>
   * @return The avatarUrl.
   */
  java.lang.String getAvatarUrl();
  /**
   * <code>string avatarUrl = 54;</code>
   * @return The bytes for avatarUrl.
   */
  com.google.protobuf.ByteString
      getAvatarUrlBytes();

  /**
   * <code>int64 gender = 55;</code>
   * @return The gender.
   */
  long getGender();

  /**
   * <code>string country = 56;</code>
   * @return The country.
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 56;</code>
   * @return The bytes for country.
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>string province = 57;</code>
   * @return The province.
   */
  java.lang.String getProvince();
  /**
   * <code>string province = 57;</code>
   * @return The bytes for province.
   */
  com.google.protobuf.ByteString
      getProvinceBytes();

  /**
   * <code>string city = 58;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 58;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string language = 59;</code>
   * @return The language.
   */
  java.lang.String getLanguage();
  /**
   * <code>string language = 59;</code>
   * @return The bytes for language.
   */
  com.google.protobuf.ByteString
      getLanguageBytes();

  /**
   * <code>string desc = 60;</code>
   * @return The desc.
   */
  java.lang.String getDesc();
  /**
   * <code>string desc = 60;</code>
   * @return The bytes for desc.
   */
  com.google.protobuf.ByteString
      getDescBytes();

  /**
   * <code>string source = 90;</code>
   * @return The source.
   */
  java.lang.String getSource();
  /**
   * <code>string source = 90;</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <code>int64 eventId = 91;</code>
   * @return The eventId.
   */
  long getEventId();

  /**
   * <code>int64 inviterId = 92;</code>
   * @return The inviterId.
   */
  long getInviterId();

  /**
   * <code>.mojo.core.Timestamp create_time = 100;</code>
   * @return Whether the createTime field is set.
   */
  boolean hasCreateTime();
  /**
   * <code>.mojo.core.Timestamp create_time = 100;</code>
   * @return The createTime.
   */
  org.mojolang.mojo.core.Timestamp getCreateTime();
  /**
   * <code>.mojo.core.Timestamp create_time = 100;</code>
   */
  org.mojolang.mojo.core.TimestampOrBuilder getCreateTimeOrBuilder();

  /**
   * <code>.mojo.core.Timestamp update_time = 101;</code>
   * @return Whether the updateTime field is set.
   */
  boolean hasUpdateTime();
  /**
   * <code>.mojo.core.Timestamp update_time = 101;</code>
   * @return The updateTime.
   */
  org.mojolang.mojo.core.Timestamp getUpdateTime();
  /**
   * <code>.mojo.core.Timestamp update_time = 101;</code>
   */
  org.mojolang.mojo.core.TimestampOrBuilder getUpdateTimeOrBuilder();

  /**
   * <code>.mojo.core.Timestamp delete_time = 102;</code>
   * @return Whether the deleteTime field is set.
   */
  boolean hasDeleteTime();
  /**
   * <code>.mojo.core.Timestamp delete_time = 102;</code>
   * @return The deleteTime.
   */
  org.mojolang.mojo.core.Timestamp getDeleteTime();
  /**
   * <code>.mojo.core.Timestamp delete_time = 102;</code>
   */
  org.mojolang.mojo.core.TimestampOrBuilder getDeleteTimeOrBuilder();
}
