// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/v1/userinfo.proto

package user.v1;

public final class UserinfoProto {
  private UserinfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_Userinfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_Userinfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026user/v1/userinfo.proto\022\007user.v1\032\024mojo/" +
      "core/time.proto\"\250\004\n\010Userinfo\022\n\n\002id\030\001 \001(\t" +
      "\022\014\n\004name\030\002 \001(\t\022\020\n\010password\030\n \001(\t\022\r\n\005emai" +
      "l\030\013 \001(\t\022\023\n\013phoneNumber\030\014 \001(\t\022\020\n\010industry" +
      "\030\r \001(\t\022\017\n\007company\030\025 \001(\t\022\013\n\003job\030\026 \001(\t\022\014\n\004" +
      "role\030\027 \001(\t\022\020\n\010birthday\030\030 \001(\t\022\021\n\teducatio" +
      "n\030\031 \001(\t\022\r\n\005major\030\032 \001(\t\022\016\n\006openid\0303 \001(\t\022\017" +
      "\n\007unionid\0304 \001(\t\022\020\n\010nickname\0305 \001(\t\022\021\n\tava" +
      "tarUrl\0306 \001(\t\022\016\n\006gender\0307 \001(\003\022\017\n\007country\030" +
      "8 \001(\t\022\020\n\010province\0309 \001(\t\022\014\n\004city\030: \001(\t\022\020\n" +
      "\010language\030; \001(\t\022\014\n\004desc\030< \001(\t\022\016\n\006source\030" +
      "Z \001(\t\022\017\n\007eventId\030[ \001(\003\022\021\n\tinviterId\030\\ \001(" +
      "\003\022)\n\013create_time\030d \001(\0132\024.mojo.core.Times" +
      "tamp\022)\n\013update_time\030e \001(\0132\024.mojo.core.Ti" +
      "mestamp\022)\n\013delete_time\030f \001(\0132\024.mojo.core" +
      ".TimestampB0\n\007user.v1B\rUserinfoProtoP\001Z\024" +
      "/go/pkg/user/v1;userb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.core.TimeProto.getDescriptor(),
        });
    internal_static_user_v1_Userinfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_v1_Userinfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_Userinfo_descriptor,
        new java.lang.String[] { "Id", "Name", "Password", "Email", "PhoneNumber", "Industry", "Company", "Job", "Role", "Birthday", "Education", "Major", "Openid", "Unionid", "Nickname", "AvatarUrl", "Gender", "Country", "Province", "City", "Language", "Desc", "Source", "EventId", "InviterId", "CreateTime", "UpdateTime", "DeleteTime", });
    org.mojolang.mojo.core.TimeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
