logs:
  level: debug
  encode: console #json or console
  output: file
  #initFields:
    #package: prenatal.v1
    #server: quiz-server
    #version: 0.1.0
  file:
    path: ./logs/app.log
    maxSize: 100
    maxBackups: 10
    maxAge: 28
    encode: console
