// Code generated by ncraft. DO NOT EDIT.
// Rerunning ncraft will overwrite this file.
// Version: 0.1.0
// Version Date:

package main

import (
	"flag"
	"github.com/ncraft-io/ncraft/go/pkg/ncraft/config"
	"github.com/ncraft-io/ncraft/go/pkg/ncraft/logs"

	nserver "github.com/ncraft-io/ncraft-gokit/pkg/server"
	"service-go/internal/server"
)

func main() {
	// Update addresses if they have been overwritten by flags
	flag.Parse()

	var conf nserver.Config
	err := config.ScanKey("server", &conf)
	if err != nil {
		logs.Warnw("failed to get the server config", "error", err.Error())
	}

	logs.Info("starting UserUnifiedServer")
	server.Run(conf)
}
